### ISSUE TITLE
What are the units of the outputs?

### ISSUE THREAD

**Issue by Ahmed-Mohamed2021** [richard-thomas/MetOffice_NIMROD#2]
Hi Richard,

The CEDA website mentioned that the data are in mm/h*32. After applying your module, I wonder if the data will be in mm/h or mm/h*32. 

Thanks

**Comment by richard-thomas** [comment]
The data read from the file is in (short) integer format, which as you surmised needs to be divided by 32 to give mm/hour. You can look at the example code in my MSc assignment (which used an earlier version of nimrod.py):

[Hydrological modelling with real rainfall and flow data](http://richard-thomas.github.io/GIS_MSc/Hydrological_modelling_real_rainfall_and_flow_data.pdf)

The specific code fragment from within that:
```
 # Get mean rainfall that falls within catchment for this timeslot
 # Also correct for fact that NIMROD data is mm/hr * 32
 rpResult = arcpy.GetRasterProperties_management(catchResampRainRas,
 "MEAN","#")
 meanRainfallRate = float(rpResult.getOutput(0)) / 32.0```

**Comment by richard-thomas** [comment]
Closing issue as no follow-up on answer given to question and no issue with the code
